eCall.ClientAccount.Web/Models/FileManagers/FileInstanceModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace eCall.ClientAccount.Web.Models.FileManagers
{
    public class FileInstanceModel
    {
        public bool IsChecked { get; set; }
        public string Created { get; set; }
        public string Name { get; set; }
        public string FileSize { get; set; }
        public FileType FileType { get; set; }
        public string FullPath { get; set; }
    }

    public enum FileType
    {
        Directory,
        File,
        Image,
        None
    }
}

eCall.ClientAccount.Web/Models/FileManagers/FileResponseModel.cs
using System.Collections.Generic;

namespace eCall.ClientAccount.Web.Models.FileManagers
{
    public class FileResponseModel
    {
        public FileResponseModel()
        {
            Files = new List<FileInstanceModel>();
            Path = string.Empty;
        }
        public IEnumerable<FileInstanceModel> Files { get; set; }
        public string Path { get; set; }
    }
}

eCall.ClientAccount.Web/Models/FileManagers/UploadedFileModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace eCall.ClientAccount.Web.Models.FileManagers
{
    public class UploadedFileModel
    {
        public string Name { get; set; }
        public long Size { get; set; }
        public string Path { get; set; }
        public DateTime CreationDateTime { get; set; }
    }
}

eCall.ClientAccount.Web/Controllers/FileManagerController.cs
using eCall.ClientAccount.Services.Services.FileManager;
using eCall.ClientAccount.Services.Services.Security;
using eCall.ClientAccount.Web.Models.FileManagers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eCall.ClientAccount.Web.Controllers
{
    public class FileManagerController : Controller
    {
        #region Fields

        private readonly IWebUserSession _webUserSession;
        private readonly IAccessService _accessService;
        private readonly IFileManagerService _fileManagerService;

        #endregion

        #region Constructor

        public FileManagerController(
            IWebUserSession webUserSession,
            IAccessService accessserv,
            IFileManagerService fileserv)
        {
            _webUserSession = webUserSession;
            _accessService = accessserv;
            _fileManagerService = fileserv;
        }

        #endregion

        #region Methods

        // GET: FileManager
        public ActionResult Index()
        {
            if (_accessService.AccessCategory(_webUserSession.Id, HttpContext.Request.RawUrl))
            {
                return RedirectToAction("Forbidden", "Error");
            }
            var uploadedFiles = new List<UploadedFileModel>();

            var fileDto = _fileManagerService.Find(10, 0, Server.MapPath("~/SharedFiles"));

            foreach (var file in fileDto)
            {
                var fileInfo = new System.IO.FileInfo(file);

                var uploadedFile = new UploadedFileModel() { Name = System.IO.Path.GetFileName(file) };

                long sizef = fileInfo.Length;
                uploadedFile.Size = sizef / 1024;
                uploadedFile.CreationDateTime = fileInfo.CreationTime;

                uploadedFile.Path = ("SharedFiles/") + System.IO.Path.GetFileName(file);
                uploadedFiles.Add(uploadedFile);
            }

            return View(uploadedFiles);
        }

        public FileResult Download(string file)
        {
            byte[] fileBytes = System.IO.File.ReadAllBytes(Server.MapPath("~/SharedFiles/") + file);
            string fileName = file;
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase upload)
        {
            if (upload != null)
            {
                // получаем имя файла
                string fileName = System.IO.Path.GetFileName(upload.FileName);
                // сохраняем файл в папку Files в проекте
                upload.SaveAs(Server.MapPath("~/SharedFiles/" + fileName));
            }
            return RedirectToAction("Index");
        }

        public ActionResult CreateFolder()
        {

            return View();
        }



        #endregion
    }
}

eCall.ClientAccount.Web/Views/FileManager/Index.cshtml
@model IEnumerable<eCall.ClientAccount.Web.Models.FileManagers.UploadedFileModel>
@using Resources;

@{
    ViewBag.Title = Resource.FileSharing;
}

@section PageLevelPluginsStyles{
    @Styles.Render("~/Content/global/plugins/datatables/datatables.min.css")

    <link href="~/Content/global/plugins/fancybox/source/jquery.fancybox.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/global/plugins/jquery-file-upload/blueimp-gallery/blueimp-gallery.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/global/plugins/jquery-file-upload/css/jquery.fileupload.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/global/plugins/jquery-file-upload/css/jquery.fileupload-ui.css" rel="stylesheet" type="text/css" />
}

<!-- BEGIN PAGE BAR -->
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="index.html">@Resource.Main</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>@Resource.Files</span>
        </li>
    </ul>

</div>
<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->
<h3 class="page-title">
    @Resource.FileSharing
    <small>FTP</small>
</h3>
<!-- END PAGE TITLE-->

@{
    ViewBag.Title = "Upload";
}
<h3>Выберите файл для загрузки</h3>
@using (Html.BeginForm("Upload", "FileManager", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    

<div class="row">   
    <div class="col-md-3">
        <input type="file" name="upload" class="btn green fileinput">
    </div>
    
    <div class="col-md-9">        
        <button type="submit" class="btn blue start">
            <i class="fa fa-upload"></i>
            <span> Загрузить </span>
        </button>
        <button type="reset" class="btn warning cancel">
            <i class="fa fa-ban-circle"></i>
            <span> Cancel upload </span>
        </button>
        <!-- The global file processing state -->
        <span class="fileupload-process"> </span>
    </div>
    <!-- The global progress information -->
    @*<div class="col-lg-5 fileupload-progress fade">
            <!-- The global progress bar -->
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                <div class="progress-bar progress-bar-success" style="width:0%;"> </div>
            </div>
            <!-- The extended global progress information -->
            <div class="progress-extended"> &nbsp; </div>
        </div>*@
</div>
    <table role="presentation" class="table table-striped clearfix">
        <tbody class="files"> </tbody>
    </table>
}



@*<form id="fileupload" action="~/Content/global/plugins/jquery-file-upload/server/php/" method="POST" enctype="multipart/form-data">
        <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
        <div class="row fileupload-buttonbar">
            <div class="col-lg-7">
                <!-- The fileinput-button span is used to style the file input field as button -->
                <span class="btn green fileinput-button">
                    <i class="fa fa-plus"></i>
                    <span> Add files... </span>
                    <input type="file" name="files[]" multiple="">
                </span>
                <button type="submit" class="btn blue start">
                    <i class="fa fa-upload"></i>
                    <span> Start upload </span>
                </button>
                <button type="reset" class="btn warning cancel">
                    <i class="fa fa-ban-circle"></i>
                    <span> Cancel upload </span>
                </button>
                <button type="button" class="btn red delete">
                    <i class="fa fa-trash"></i>
                    <span> Delete </span>
                </button>
                <!-- The global file processing state -->
                <span class="fileupload-process"> </span>
            </div>
            <!-- The global progress information -->
            <div class="col-lg-5 fileupload-progress fade">
                <!-- The global progress bar -->
                <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                    <div class="progress-bar progress-bar-success" style="width:0%;"> </div>
                </div>
                <!-- The extended global progress information -->
                <div class="progress-extended"> &nbsp; </div>
            </div>
        </div>
        <!-- The table listing the files available for upload/download -->
        <table role="presentation" class="table table-striped clearfix">
            <tbody class="files"> </tbody>
        </table>
    </form>*@


<table class="table table-striped table-bordered table-hover order-column" id="sample_3">
    <thead>
        <tr> 
            <th style="width:70px">Действие</th>
            <th class="table-item-title table-item-w70">Имя</th>
            <th>Размер</th>
            <th class="hmax480">Создано</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>         
            <td><a href="@Url.Action("Download", new { file = item.Name})" class="btn blue start">Скачать</a></td>
            <td>@Html.DisplayFor(model => item.Name)</td>
            <td>@Html.DisplayFor(model => item.Size) kB</td>
            <td>@Html.DisplayFor(model => item.CreationDateTime)</td>
        </tr>
        }
    </tbody>
</table>


<!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
<script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger label label-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0">
                <div class="progress-bar progress-bar-success" style="width:0%;"></div>
            </div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
            <button class="btn blue start" disabled>
                <i class="fa fa-upload"></i>
                <span>Start</span>
            </button> {% } %} {% if (!i) { %}
            <button class="btn red cancel">
                <i class="fa fa-ban"></i>
                <span>Cancel</span>
            </button> {% } %}
        </td>
    </tr> {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery>
                    <img src="{%=file.thumbnailUrl%}">
                </a> {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl? 'data-gallery' : '' %}>{%=file.name%}</a> {% } else { %}
                <span>{%=file.name%}</span> {% } %}
            </p> {% if (file.error) { %}
            <div>
                <span class="label label-danger">Error</span> {%=file.error%}
            </div> {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.deleteUrl) { %}
            <button class="btn red delete btn-sm" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}" {% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}' {% } %}>
                <i class="fa fa-trash-o"></i>
                <span>Delete</span>
            </button>
            <input type="checkbox" name="delete" value="1" class="toggle"> {% } else { %}
            <button class="btn yellow cancel btn-sm">
                <i class="fa fa-ban"></i>
                <span>Cancel</span>
            </button> {% } %}
        </td>
    </tr> {% } %}
</script>

@section PageLevelPluginsScript {
    @Scripts.Render("~/Scripts/jquery.unobtrusive-ajax.min.js")
    @Scripts.Render("~/Content/global/scripts/datatable.js")
    @Scripts.Render("~/Content/global/plugins/datatables/datatables.min.js")
    @Scripts.Render("~/Content/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js")

    <script src="~/Content/global/plugins/fancybox/source/jquery.fancybox.pack.js" type="text/javascript"></script>
    <script src="~/Content/global/plugins/jquery-file-upload/js/vendor/jquery.ui.widget.js" type="text/javascript"></script>
    <script src="~/Content/global/plugins/jquery-file-upload/js/vendor/tmpl.min.js" type="text/javascript"></script>
    <script src="~/Content/global/plugins/jquery-file-upload/js/vendor/load-image.min.js" type="text/javascript"></script>
    <script src="~/Content/global/plugins/jquery-file-upload/js/vendor/canvas-to-blob.min.js" type="text/javascript"></script>
    <script src="~/Content/global/plugins/jquery-file-upload/blueimp-gallery/jquery.blueimp-gallery.min.js" type="text/javascript"></script>
    <script src="~/Content/global/plugins/jquery-file-upload/js/jquery.iframe-transport.js" type="text/javascript"></script>
    <script src="~/Content/global/plugins/jquery-file-upload/js/jquery.fileupload.js" type="text/javascript"></script>
    <script src="~/Content/global/plugins/jquery-file-upload/js/jquery.fileupload-process.js" type="text/javascript"></script>
    <script src="~/Content/global/plugins/jquery-file-upload/js/jquery.fileupload-image.js" type="text/javascript"></script>
    <script src="~/Content/global/plugins/jquery-file-upload/js/jquery.fileupload-audio.js" type="text/javascript"></script>
    <script src="~/Content/global/plugins/jquery-file-upload/js/jquery.fileupload-video.js" type="text/javascript"></script>
    <script src="~/Content/global/plugins/jquery-file-upload/js/jquery.fileupload-validate.js" type="text/javascript"></script>
    <script src="~/Content/global/plugins/jquery-file-upload/js/jquery.fileupload-ui.js" type="text/javascript"></script>
}


@section PageLevelScripts{
    @Scripts.Render("~/Scripts/Pages/table-datatables-managed.js")
    <script src="~/Scripts/Pages/form-fileupload.js"></script>
}