eCall.ClientAccount.Web/Models/Grades/MoodleReportViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using eCall.Moodle;
using System.Web.Mvc;

namespace eCall.ClientAccount.Web.Models.Grades
{
    public class MoodleReportViewModel
    {
        public string CategoryId { get; set; }
        public string CohortId { get; set; }
        public IList<SelectListItem> Users { get; set; }
        public IList<SelectListItem> Courses { get; set; }
        public DateTime? DateFrom { get; set; }
        public DateTime? DateTo { get; set; }
        public bool HasDates => DateFrom.HasValue && DateTo.HasValue;
        public string UserId { get; set; }
        public bool HasUserId => string.IsNullOrEmpty(UserId) || UserId == "-1" ? false : true;
        public string CourseId { get; set; }
        public bool HasCourseId => string.IsNullOrEmpty(CourseId) || CourseId == "-1" ? false : true;
    }
}

eCall.ClientAccount.Web/Controllers/GradeController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using eCall.Moodle;
using eCall.ClientAccount.Web.Models.Grades;

namespace eCall.ClientAccount.Web.Controllers
{
    public class GradeController : Controller
    {
        private readonly MoodleApi _api;
        public GradeController()
        {
            _api = new MoodleApi(
                ConfigurationManager.AppSettings["moodle.login"]
                ,ConfigurationManager.AppSettings["moodle.pass"]
                ,ConfigurationManager.AppSettings["moodle.token"]
                ,ConfigurationManager.AppSettings["moodle.url"]
                );
        }
        public ActionResult MoodleReport(string id, string categoryId, string cohortId)
        {
            var model = new MoodleReportViewModel();

            model.CategoryId = categoryId;
            model.CohortId = cohortId;
            model.CourseId = id;
            model.DateFrom = DateTime.Today.AddDays(-10);
            model.DateTo = DateTime.Today;

            if (!string.IsNullOrEmpty(categoryId))
            {
                var coursers = _api.GetCourses(categoryId);
                model.Courses = coursers.OrderBy(x=> x.FullName).Select(x => new SelectListItem() { Value = x.Id.ToString(), Text = x.FullName }).ToList();
            }

            if (!string.IsNullOrEmpty(cohortId))
            {
                var users = _api.GetUsers(cohortId, true);
                model.Users = users.OrderBy(x=> x.FullName).Select(x => new SelectListItem() { Value = x.Id.ToString(), Text = x.FullName }).ToList();
                model.Users.Insert(0, new SelectListItem() { Value = "-1", Text = "---" });
            }

            return View("MoodleReport", model);
        }

        public ActionResult GetMoodleReport(MoodleReportViewModel model)
        {
            IList<MoodleReportGradeItem> list;
            if (!string.IsNullOrEmpty(model.CourseId))
                list = _api.GetGradeItems(model.CourseId);
            else
                list = new List<MoodleReportGradeItem>();

            list = list.ToList().FindAll(x =>
                                (!model.HasUserId || model.UserId == x.UserId) &&
                                (!model.HasDates || (x.Completed >= model.DateFrom && x.Completed <= model.DateTo))).ToList();

            return View("_MoodleReport", list);
        }

        public string GetMoodleAttempt(string id)
        {
            var res = _api.GetAttemptHtml(id);
            return res;
        }
    }
}

eCall.ClientAccount.Web/Views/Grade/MoodleReport.cshtml
@using Resources;
@using eCall.Moodle;

@model eCall.ClientAccount.Web.Models.Grades.MoodleReportViewModel

@{
    ViewBag.Title = "Оценки";
    ViewBag.Sub = "Знания";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section PageLevelPluginsStyles{
    @Styles.Render("~/Content/global/plugins/datatables/datatables.min.css")
    @Styles.Render("~/Content/global/plugins/bootstrap-daterangepicker/daterangepicker.min.css")
    @Styles.Render("~/Content/global/plugins/bootstrap-datetimepicker/css/bootstrap-datetimepicker.min.css")
}


<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="@Url.Action("Index", "Home")">@Resource.Main</a>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>@ViewBag.Title</span>
            <i class="fa fa-circle"></i>
        </li>
        <li>
            <span>@ViewBag.Sub</span>
        </li>
    </ul>
</div>



<h3 class="page-title">
    Оценка знаний
</h3>

<form id="optsForm" action="@Url.Action("GetMoodleReport", "Grade")">
    <div class="portlet box blue">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-filter font-purple"></i>
                <span class="caption-subject font-purple bold uppercase">@Resource.Filter</span>
            </div>
            <div class="actions">
                <div class="btn-group">
                    <button type="submit" class="btn green sbold uppercase btn-outline btn-circle btn-sm reload" id="blockui_sample_4_1">
                        @Resource.Apply <i class="fa fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
        <div class="portlet-body">
            <div class="form-body">
                <div class="row">
                    @Html.HiddenFor(m => m.CategoryId)
                    @Html.HiddenFor(m => m.CohortId)
                    @if (!Model.HasCourseId)
                    {
                    <div class="col-md-2">
                        <span class="help-block">@Resources.Resource.Course</span>
                        @Html.DropDownListFor(m => m.CourseId, Model.Courses, new { @class = "form-control" })
                    </div>
                    } else
                    {
                        @Html.HiddenFor(m=> m.CourseId)
                    }
                    <div class="col-md-2" style="display:inline;">
                        <span class="help-block">@Resource.PeriodStart</span>
                        <div class='input-group date form_date' id="datefrom">
                            <input name="DateFrom" id="DateFrom" type='text' class="form-control dtp-custom" value="@Model.DateFrom" />
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <span class="help-block">@Resource.PeriodEnd</span>
                        <div class='input-group date form_date' id="dateto">
                            <input name="DateTo" id="DateTo" type="text" class="form-control dtp-custom" value="@Model.DateTo" />
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-calendar"></span>
                            </span>
                        </div>
                    </div>
                    @if (Model.Users != null && Model.Users.Count > 1) {
                    <div class="col-md-2">
                        <span class="help-block">@Resources.Resource.Operator</span>
                        @Html.DropDownListFor(m => m.UserId, Model.Users, new { @class = "form-control" })
                    </div>
                    } else
                    {
                        @Html.HiddenFor(m=> m.UserId)
                    }
                </div>
            </div>
        </div>
    </div>
</form>

<div id="results"></div>


@section PageLevelPluginsScript {
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    @Scripts.Render("~/Content/global/scripts/datatable.js")
    @Scripts.Render("~/Content/global/plugins/datatables/datatables.min.js")
    @Scripts.Render("~/Content/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js")

    <script src="~/Content/global/plugins/morris/morris.min.js" type="text/javascript"></script>
    <script src="~/Content/global/plugins/morris/raphael-min.js" type="text/javascript"></script>
    <script src="~/Scripts/moment.js" type="text/javascript"></script>
    <script src="~/Content/global/plugins/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js" type="text/javascript"></script>
}

@section PageLevelScripts{
    @*<script src="~/Scripts/Pages/table-datatables-buttons.min.js"></script>
        <script src="~/Scripts/Pages/components-date-time-pickers.js"></script>*@
    <script src="~/Scripts/Pages/ui-blockui.js"></script>

    <script type="text/javascript">

        // this is the id of the form
        $("#optsForm").submit(function (e) {
            var form = $(this);
            var url = form.attr('action');

            $.ajax({
                type: "POST",
                url: url,
                data: form.serialize(), // serializes the form's elements.
                success: function (data) {
                    $("#results").html(data);
                }
            });

            e.preventDefault(); // avoid to execute the actual submit of the form.

            App.blockUI({
                target: '#results',
                boxed: true,
                message: 'Loading...'
            });

            window.setTimeout(function () {
                App.unblockUI('#results');
            }, 100000);
        });


        $(".form_date").datetimepicker({
            useCurrent: true,
            keepOpen: false,
            locale: moment.locale(),
            format: 'DD.MM.YYYY' //'DD.MM.YYYY HH:mm'
        });


    </script>

}

eCall.ClientAccount.Web/Views/Grade/_MoodleReport.cshtml
@using eCall.Moodle;
@model IEnumerable<MoodleReportGradeItem>

@{ 
    Layout = null;
}

<div class="row">
    <div class="col-md-12">
        <div class="portlet box red">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-globe"></i>@Resources.Resource.Report
                </div>
                <div class="tools"> </div>
            </div>
            <div class="portlet-body">

                <table class="table table-striped table-bordered table-hover" id="sample_2">
                    <thead>
                        <tr>
                            <th> @Html.DisplayNameFor(model => model.UserName) </th>
                            <th> @Html.DisplayNameFor(model => model.UserEmail) </th>
                            <th> @Html.DisplayNameFor(model => model.State) </th>
                            <th> @Html.DisplayNameFor(model => model.StartedOn) </th>
                            <th> @Html.DisplayNameFor(model => model.Completed) </th>
                            <th> @Html.DisplayNameFor(model => model.TakenTime) </th>
                            <th> @Html.DisplayNameFor(model => model.FinalGrade) </th>
                            <th> @Html.DisplayNameFor(model => model.AttemptId) </th>

                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td> @Html.DisplayFor(modelItem => item.UserName) </td>
                            <td> @Html.DisplayFor(modelItem => item.UserEmail) </td>
                            <td> @Html.DisplayFor(modelItem => item.State) </td>
                            <td> @Html.DisplayFor(modelItem => item.StartedOn) </td>
                            <td> @Html.DisplayFor(modelItem => item.Completed) </td>
                            <td> @Html.DisplayFor(modelItem => item.TakenTime) </td>
                            <td> @Html.DisplayFor(modelItem => item.FinalGrade) </td>
                            <td> <button type="button" class="btn btn-default btn-sm" onclick="showDetails(@item.AttemptId)">Details</button> </td>
                            </tr>
                        }
                </table>
            </div>
        </div>
    </div>
</div>

<div id="modDialog" class="modal fade" tabindex="-1" aria-hidden="true">
    <div id="dialogContent" class="modal-dialog modal-lg"></div>
</div>

<script src="~/Scripts/Pages/table-datatables-buttons.min.js"></script>

<script type="text/javascript">

    function showDetails(id) {
            $.ajax({
                url: '/Grade/GetMoodleAttempt',
                data: {
                    'id': id
                },
                success: function (html) {
                    bootbox.alert({
                        size: "large",
                        message: html,
                        buttons: {
                            ok: {
                                label: 'OK',
                                className: 'btn-default'
                            }
                        }
                    });
                }
            });
    }
</script>