eCall.ClientAccount.Web/Controllers/CallRecordController.cs
using eCall.ClientAccount.Services.Services.IPCC;
using eCall.ClientAccount.Services.Services.Security;
using eCall.ClientAccount.Services.Services.TrueRS;
using eCall.ClientAccount.Web.Filter;
using eCall.ClientAccount.Web.Mapper;
using eCall.ClientAccount.Web.Models.CallRecords;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eCall.ClientAccount.Web.Controllers
{
    [ClientAuthorize(Roles = "CAManager, CAUser, CAAdmin")]
    public class CallRecordController : Controller
    {
        #region Fields

        private readonly IWebUserSession _webUserSession;
        private readonly ISkillGroupRecordService _skillGroupRecordService;
        private readonly IAgentRecordService _agentRecordService;
        private readonly IVoiceRecordService _voiceRecordService;
        private readonly IAccessService _accessService;

        #endregion

        #region Constructor

        public CallRecordController(
            IWebUserSession webUserSession,
            ISkillGroupRecordService sgserv,
            IAgentRecordService agentserv,
            IVoiceRecordService vrserv,
            IAccessService accessserv)
        {
            _webUserSession = webUserSession;
            _skillGroupRecordService = sgserv;
            _agentRecordService = agentserv;
            _voiceRecordService = vrserv;
            _accessService = accessserv;
        }

        #endregion

        #region Methods

        public ActionResult RecordIn()
        {
            if(_accessService.AccessCategory(_webUserSession.Id, HttpContext.Request.RawUrl))
            {
                return RedirectToAction("Forbidden", "Error");
            }

            var model = new FindRecordModel
            {
                AvailableSkillGroup = GetAvailableSkillGroup(_webUserSession.Id, "Inbound"),
                AvailableAgent = GetAvailableAgent(_webUserSession.Id, "Inbound")
            };
            return View("RecordIn", model);
        }

        public ActionResult RecordOut()
        {
            if (_accessService.AccessCategory(_webUserSession.Id, HttpContext.Request.RawUrl))
            {
                return RedirectToAction("Forbidden", "Error");
            }

            var model = new FindRecordModel
            {
                AvailableSkillGroup = GetAvailableSkillGroup(_webUserSession.Id, "Outbound"),
                AvailableAgent = GetAvailableAgent(_webUserSession.Id, "Outbound")
            };
            return View("RecordOut", model);
        }

        [HttpPost]
        public ActionResult RecordOutSearch(FindRecordModel findrecord)
        {
            var voiceDto = _voiceRecordService.GetRecordByCustomer(Convert.ToDateTime(findrecord.StartDate), Convert.ToDateTime(findrecord.EndDate), findrecord.SkillGroupId.ToString(), findrecord.Phone, findrecord.AgentId.ToString(), findrecord.Top, _webUserSession.Id, "Outbound", findrecord.MinDuration, findrecord.MaxDuration);
            var model = voiceDto.Select(x => x.ToModel()).ToList();

            return PartialView("RecordOutSearch", model);
        }

        [HttpPost]
        public ActionResult RecordInSearch(FindRecordModel findrecord)
        {
            var dateFrom = Convert.ToDateTime(findrecord.StartDate);
            var dateTo = Convert.ToDateTime(findrecord.EndDate); //.AddDays(1).AddMilliseconds(-1);
            var voiceDto = _voiceRecordService.GetRecordByCustomer(dateFrom, dateTo, findrecord.SkillGroupId.ToString(), findrecord.Phone, findrecord.AgentId.ToString(), findrecord.Top, _webUserSession.Id, "Inbound", findrecord.MinDuration, findrecord.MaxDuration);
            var model = voiceDto.Select(x => x.ToModel()).ToList();
            if (findrecord.EndCall != "All")
            {
                model = model.Where(x => x.EndCall == findrecord.EndCall).ToList();
            }
            //else
            //{
            //    var model = voiceDto.Select(x => x.ToModel()).Where(x => x.EndCall == findrecord.EndCall).ToList();
            //}            

            return PartialView("RecordInSearch", model);
        }

        public ActionResult Details(int id)
        {
            //var recordDto = _voiceRecordService.GetRecordById(id, Server.MapPath("~/Media"), Request.Browser.Browser);
            //var model = recordDto.Select(x => x.ToModel()).ToList();

            var recordDto = _voiceRecordService.GetMP3RecordById(id, Server.MapPath("~/Media"), Request.Browser.Browser);
            
            var model = recordDto.ToModel();
            return PartialView(model);
        }

        //public PartialViewResult RepairIn(string id)
        //{
        //    //string ID = GetSTID(id);
        //    if (id != null && id != "")
        //    {
        //        //SQL.Update(" update vrVoiceRecords set stID=" + ID + " where vrID=" + id);
        //        //SQL.Update(" update vrVoiceRecords set stID=" + ID + " where vrParentID=" + id);
        //    }
        //    return PartialView("Details", new { id });
        //}

        #endregion

        #region Util

        private IList<SelectListItem> GetAvailableSkillGroup(int userId, string type)
        {
            var SkillGroup = new List<SelectListItem>();
            var sg = (_skillGroupRecordService.GetSGRecordForCustomer(userId, type))
                .Select(d => new SelectListItem { Text = d.EnterpriseName, Value = d.SkillsetID.ToString() })
                .ToList();
            if (sg.Count == 0)
                SkillGroup.Add(new SelectListItem { Text = "Нет доступных SkillGroup", Value = "", Selected = true });
            else
            {
                SkillGroup.Add(new SelectListItem { Text = "Все SkillGroup", Value = "-1", Selected = true });
                SkillGroup.AddRange(sg);
            }                
            return SkillGroup;
        }

        private IList<SelectListItem> GetAvailableAgent(int userId, string type)
        {
            var Agent = new List<SelectListItem>();

            var agent = (_agentRecordService.GetAgentBySG(userId, type))
                .Select(d => new SelectListItem { Text = d.EnterpriseName, Value = d.SkillTargetID.ToString() })
                .ToList();
            if (agent.Count == 0)
                Agent.Add(new SelectListItem { Text = "Нет доступных операторов", Value = "", Selected = true });
            else
            {
                Agent.Add(new SelectListItem { Text = "Все операторы", Value = "-1", Selected = true });
                Agent.AddRange(agent);
            }
                
            return Agent;
        }

        #endregion        
    }
}

eCall.ClientAccount.Web/Controllers/CatalogController.cs
using eCall.ClientAccount.Services.DTO.Catalog;
using eCall.ClientAccount.Services.Services.Catalog;
using eCall.ClientAccount.Services.Services.Security;
using eCall.ClientAccount.Web.Mapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eCall.ClientAccount.Web.Controllers
{
    public class CatalogController : Controller
    {
        #region Fields

        private readonly IWebUserSession _webUserSession;
        private readonly ICategoryService _categoryService;

        #endregion

        #region Constructor

        public CatalogController(
            IWebUserSession webUserSession, 
            ICategoryService catsrv)
        {
            _webUserSession = webUserSession;
            _categoryService = catsrv;            
        }

        #endregion

        #region Methods

        // GET: Catalog
        public ActionResult Index()
        {
            return View();
        }

        //category
        [ChildActionOnly]
        public ActionResult Category()
        {
            IEnumerable<CategoryDTO> categpryDtos = _categoryService.GetAllCategoryForCustomer(_webUserSession.Id);
            var category = categpryDtos.Select(x => x.ToModel()).ToList();

            IEnumerable<ReportCategoryDTO> reportDtos = _categoryService.GetAllReportCategoryForCustomer(_webUserSession.Id);            
            var report = reportDtos.Select(x => x.ToModel()).ToList();

            ViewBag.reportForCustomer = report.ToList();

            return PartialView(category);
        }

        #endregion
    }
}

eCall.ClientAccount.Web/Controllers/CommonController.cs
using eCall.ClientAccount.Web.Filter;
using eCall.ClientAccount.Web.Models.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eCall.ClientAccount.Web.Controllers
{
    [ClientAuthorize(Roles = "CAManager, CAUser, CAAdmin")]
    public class CommonController : Controller
    {
        #region Fields

        #endregion

        #region Constructors

        #endregion

        #region Methods

        //logo
        [ChildActionOnly]
        public virtual ActionResult Logo()
        {
            string src = Url.Content("~/Content/layouts/layout/img/Logo_red.png");
            //var model = _commonModelFactory.PrepareLogoModel();
            var model = new LogoModel { LogoPath = src, StoreName = "eBilling" };

            return PartialView(model);
        }

        //language
        [ChildActionOnly]
        public virtual ActionResult LanguageSelector()
        {
            //var model = _commonModelFactory.PrepareLanguageSelectorModel();

            //if (model.AvailableLanguages.Count == 1)
            //    Content("");

            return PartialView(/*model*/);
        }

        //language        
        public virtual ActionResult ChangeCulture(string lang)
        {
            //var model = _commonModelFactory.PrepareLanguageSelectorModel();

            //if (model.AvailableLanguages.Count == 1)
            //    Content("");

            //return PartialView(/*model*/);
            string returnUrl = Request.UrlReferrer.AbsolutePath;
            // Список культур
            List<string> cultures = new List<string>() { "ru", "uk" };
            if (!cultures.Contains(lang))
            {
                lang = "uk";
            }
            // Сохраняем выбранную культуру в куки
            HttpCookie cookie = Request.Cookies["lang"];
            if (cookie != null)
                cookie.Value = lang;   // если куки уже установлено, то обновляем значение
            else
            {

                cookie = new HttpCookie("lang");
                cookie.HttpOnly = false;
                cookie.Value = lang;
                cookie.Expires = DateTime.Now.AddYears(1);
            }
            Response.Cookies.Add(cookie);
            return Redirect(returnUrl);
        }

        //footer
        [ChildActionOnly]
        public virtual ActionResult Footer()
        {
            //var model = _commonModelFactory.PrepareFooterModel();
            return PartialView(/*model*/);
        }

        //favicon
        [ChildActionOnly]
        public virtual ActionResult Favicon()
        {
            var model = "~/favicon.ico";
            //var model = _commonModelFactory.PrepareFaviconModel();
            //if (String.IsNullOrEmpty(model.FaviconUrl))
            //    return Content("");

            return PartialView(model);
        }

        #endregion
    }
}

eCall.ClientAccount.Web/Controllers/StatisticController.cs
using eCall.ClientAccount.Services.DTO.Statistics;
using eCall.ClientAccount.Services.Services.Reports;
using eCall.ClientAccount.Services.Services.Security;
using eCall.ClientAccount.Services.Services.TrueRS;
using eCall.ClientAccount.Web.Mapper;
using eCall.ClientAccount.Web.Models.Statistics;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eCall.ClientAccount.Web.Controllers
{
    public class StatisticController : Controller
    {
        #region Fields

        private readonly IWebUserSession _webUserSession;
        private readonly IAccessService _accessService;
        private readonly ICallTypeReportService _callTypeReportService;
        private readonly ISkillGroupReportService _skillGroupReportService;
        private readonly IStatisticsReportService _statisticsReportService;

        #endregion

        #region Constructor

        public StatisticController(
            IWebUserSession webUserSession,
            IAccessService accessserv,
            ICallTypeReportService ctserv,
            ISkillGroupReportService sgserv,
            IStatisticsReportService statserv)
        {
            _webUserSession = webUserSession;
            _accessService = accessserv;
            _callTypeReportService = ctserv;
            _skillGroupReportService = sgserv;
            _statisticsReportService = statserv;
        }

        #endregion

        #region Methods

        // GET: Statistic
        public ActionResult StatisticInb()
        {
            if (_accessService.AccessCategory(_webUserSession.Id, HttpContext.Request.RawUrl))
            {
                return RedirectToAction("Forbidden", "Error");
            }

            StatisticsFindModel model = new StatisticsFindModel
            {
                AvailableSkillGroup = GetAvailableSkillGroup(_webUserSession.Id, "Inbound")
            };

            return View(model);
        }

        [HttpPost]
        // GET: Statistic
        public ActionResult StatisticInbSearch(string sd, string ed, string SkillGroupId)
        {
            var statisticsDTO = _statisticsReportService.GetStatisticsInbSearch(sd, ed, SkillGroupId, _webUserSession.Id, "Inbound");
            var model = statisticsDTO.Select(x => x.ToModel()).ToList();
          
            return PartialView(model);
        }

        public ActionResult StatisticOut()
        {
            if (_accessService.AccessCategory(_webUserSession.Id, HttpContext.Request.RawUrl))
            {
                return RedirectToAction("Forbidden", "Error");
            }

            return View();
        }

        public ActionResult StatisticOutSearch(string sd, string ed)
        {
            List<StatisticsOutStatusCallDTO> liststatusCallDTO;
            List<StatisticsOutStatusDTO> liststatusDTO;
            List<StatisticsOutStatusNotCallDTO> liststatusNotCallDTO;

            _statisticsReportService.GetStatisticsOut(sd, ed, out liststatusCallDTO, out liststatusDTO, out liststatusNotCallDTO);

            ViewBag.StatusCall = liststatusCallDTO.Select(x => x.ToModel()).ToList();
            ViewBag.Statu = liststatusDTO.Select(x => x.ToModel()).ToList();
            ViewBag.StatusNotCall = liststatusNotCallDTO.Select(x => x.ToModel()).ToList();

            return PartialView();
        }

        //GetStatisticsOut

        #endregion

        #region Util

        private IList<SelectListItem> GetAvailableSkillGroup(int userId, string type)
        {
            var SkillGroup = new List<SelectListItem>();
            var sg = (_skillGroupReportService.GetSGRecordForCustomer(userId, type))
                .Select(d => new SelectListItem { Text = d.EnterpriseName, Value = d.SkillTargetID.ToString() })
                .ToList();
            if (sg.Count == 0)
                SkillGroup.Add(new SelectListItem { Text = "Нет доступных SkillGroup", Value = "", Selected = true });
            else
            {
                SkillGroup.Add(new SelectListItem { Text = "Все SkillGroup", Value = "-1", Selected = true });
                SkillGroup.AddRange(sg);
            }
            return SkillGroup;
        }

        #endregion
    }
}

eCall.ClientAccount.Web/Views/Shared/_Header.cshtml
<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top">
    <!-- BEGIN HEADER INNER -->
    <div class="page-header-inner ">
        <!-- BEGIN LOGO -->
        @Html.Action("Logo", "Common", new { area = "" })
        <!-- END LOGO -->
        @Html.Partial("_HorMenu")
        <!-- BEGIN HEADER SEARCH BOX -->
        <!-- DOC: Apply "search-form-expanded" right after the "search-form" class to have half expanded search box -->
        @*<form class="search-form" action="extra_search.html" method="GET">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search..." name="query">
                <span class="input-group-btn">
                    <a href="javascript:;" class="btn submit">
                        <i class="icon-magnifier"></i>
                    </a>
                </span>
            </div>
        </form>*@
        <!-- END HEADER SEARCH BOX -->
        <!-- BEGIN RESPONSIVE MENU TOGGLER -->
        <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
            <span></span>
        </a>
        <!-- END RESPONSIVE MENU TOGGLER -->
        <!-- BEGIN TOP NAVIGATION MENU -->
        <div class="top-menu">
            <ul class="nav navbar-nav pull-right">
                @Html.Action("LanguageSelector", "Common", new { area = "" })
                <!-- BEGIN USER LOGIN DROPDOWN -->
                <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                <li class="dropdown dropdown-user">
                    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                        <img alt="" class="img-circle" src="~/Content/layouts/layout/img/avatar.png" />
                        <span class="username username-hide-on-mobile"> @User.Identity.Name.ToString() </span>
                        <i class="fa fa-angle-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-default">
                        @*<li>
                            <a href="page_user_profile_1.html">
                                <i class="icon-user"></i> My Profile
                            </a>
                        </li>
                        <li>
                            <a href="app_calendar.html">
                                <i class="icon-calendar"></i> My Calendar
                            </a>
                        </li>
                        <li>
                            <a href="app_inbox.html">
                                <i class="icon-envelope-open"></i> My Inbox
                                <span class="badge badge-danger"> 3 </span>
                            </a>
                        </li>
                        <li>
                            <a href="app_todo.html">
                                <i class="icon-rocket"></i> My Tasks
                                <span class="badge badge-success"> 7 </span>
                            </a>
                        </li>
                        <li class="divider"> </li>*@
                        <li>
                            <a href="page_user_lock_1.html">
                                <i class="icon-lock"></i> Блокировать
                            </a>
                        </li>
                        <li>
                            <a href="/Account/Logout">
                                <i class="icon-key"></i> Выход
                            </a>
                        </li>
                    </ul>
                </li>
                <!-- END USER LOGIN DROPDOWN -->                
            </ul>
        </div>
        <!-- END TOP NAVIGATION MENU -->
    </div>
    <!-- END HEADER INNER -->
</div>
<!-- END HEADER -->

eCall.ClientAccount.Web/Views/Shared/_HorMenu.cshtml
<!-- BEGIN MEGA MENU -->
<!-- DOC: Remove "hor-menu-light" class to have a horizontal menu with theme background instead of white background -->
<!-- DOC: This is desktop version of the horizontal menu. The mobile version is defined(duplicated) in the responsive menu below along with sidebar menu. So the horizontal menu has 2 seperate versions -->
<div class="hor-menu   hidden-sm hidden-xs">
    <ul class="nav navbar-nav">
        <li class="classic-menu-dropdown ">
            <a href="@Url.Action("Index", "Home")">
                <i class="icon-home"></i> @Resources.Resource.Main
                <span class="selected"> </span>
            </a>
        </li>
        @Html.Action("Category", "Catalog")
        <!-- DOC: Remove data-hover="megamenu-dropdown" and data-close-others="true" attributes below to disable the horizontal opening on mouse hover -->
        @*<li class="classic-menu-dropdown">
            <a href="javascript:;" data-hover="megamenu-dropdown" data-close-others="true">
                <i class="icon-call-end"></i> Онлайн статистика
                <i class="fa fa-angle-down"></i>
                
            </a>
            <ul class="dropdown-menu pull-left">
                <li>
                    <a href="@Url.Action("StatisticInb", "Statistic")">
                        <i class="icon-call-in"></i> Входящие
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("StatisticOut", "Statistic")">
                        <i class="icon-call-out"></i> Исходящие
                    </a>
                </li>                
            </ul>
        </li>*@
        @*<li class="classic-menu-dropdown">
            <a href="javascript:;" data-hover="megamenu-dropdown" data-close-others="true">
                <i class="icon-notebook"></i> Отчеты
                <i class="fa fa-angle-down"></i>
                
            </a>
            <ul class="dropdown-menu pull-left">
                <li>
                    <a href="@Url.Action("", "")">
                        <i class="icon-login"></i> Test
                    </a>
                </li>                
            </ul>
        </li>
        <li class="classic-menu-dropdown">
            <a href="javascript:;" data-hover="megamenu-dropdown" data-close-others="true">
                <i class="icon-music-tone"></i> Записи звонков
                <i class="fa fa-angle-down"></i>                
            </a>
            <ul class="dropdown-menu pull-left">
                <li>
                    <a href="@Url.Action("RecordIn", "CallRecord")">
                        <i class="icon-login"></i> Входящие
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("RecordOut", "CallRecord")">
                        <i class="icon-logout"></i> Исходящие
                    </a>
                </li>
            </ul>
        </li>*@
        @*<li class="classic-menu-dropdown">
            <a href="#">
                <i class="icon-dislike"></i> Отчет о жалобах
            </a>
        </li>
        <li class="classic-menu-dropdown">
            <a href="#">
                CR
            </a>

        </li>*@
        @*<li class="classic-menu-dropdown">
            <a href="#">
                <i class="icon-users"></i> Крок                
            </a>
            
        </li>
        <li class="classic-menu-dropdown">
            <a href="#">
                <i class="icon-share-alt"></i> Файлы
            </a>
            
        </li>*@
    </ul>
</div>
<!-- END MEGA MENU -->

eCall.ClientAccount.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – Client</title>
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
    @Styles.Render("~/Content/global/plugins/font-awesome/css/font-awesome.min.css")
    @Styles.Render("~/Content/global/plugins/simple-line-icons/simple-line-icons.min.css")
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />

    @RenderSection("PageLevelPluginsStyles", required: false)
    <link href="~/Content/global/css/components.min.css" rel="stylesheet" id="style_components" type="text/css" />
    @Styles.Render("~/Content/global/css/plugins.min.css")
    @Styles.Render("~/Content/layouts/layout/css/layout.min.css")
    <link href="~/Content/layouts/layout/css/themes/darkblue.min.css" rel="stylesheet" type="text/css" id="style_color" />
    @Styles.Render("~/Content/layouts/layout/css/custom.min.css")
    <link rel="shortcut icon" href="../favicon.ico" />
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="page-header-fixed page-sidebar-closed-hide-logo page-content-white page-full-width">
    @Html.Partial("_Header")
    <div class="clearfix"> </div>
    <div class="page-container">
        @Html.Partial("_Sidebar")
        <div class="page-content-wrapper">
            <div class="page-content">
                @RenderBody()
            </div>
        </div>
        @*<a href="javascript:;" class="page-quick-sidebar-toggler">
                <i class="icon-login"></i>
            </a>*@
    </div>
    @Html.Action("Footer", "Common", new { area = "" })
    <!--[if lt IE 9]>
    <script src="~/Content/global/plugins/respond.min.js"></script>
    <script src="~/Content/global/plugins/excanvas.min.js"></script>
    <![endif]-->
    <script type="text/javascript" src="~/Content/global/scripts/cisco.js"></script>

    @Scripts.Render("~/Scripts/jquery-3.2.1.js")
    @Scripts.Render("~/Scripts/bootstrap.js")
    @*@Scripts.Render("~/Scripts/respond.js")*@
    @Scripts.Render("~/Content/global/plugins/js.cookie.min.js")
    @Scripts.Render("~/Content/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js")
    @Scripts.Render("~/Content/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js")
    @Scripts.Render("~/Content/global/plugins/jquery.blockui.min.js")
    @Scripts.Render("~/Content/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js")
    @Scripts.Render("~/Content/global/plugins/bootbox/bootbox.min.js")
    @RenderSection("PageLevelPluginsScript", required: false)
    @Scripts.Render("~/Content/global/scripts/app.min.js")
    @RenderSection("PageLevelScripts", required: false)
    @Scripts.Render("~/Content/layouts/layout/scripts/layout.js")
    @Scripts.Render("~/Content/layouts/layout/scripts/demo.min.js")
    @*@Scripts.Render("~/Content/layouts/global/scripts/quick-sidebar.min.js")*@
    @if (!string.IsNullOrEmpty(ViewBag.CurrentPage))
    {
        <script type="text/javascript">
        $(function () {
            //$("li[title=@ViewBag.CurrentPage]").prev().parents("li ul").prev().addClass("active");
            $("li[title=@ViewBag.CurrentPage]").addClass("active");

        });

        </script>
    }
</body>
</html>

eCall.ClientAccount.Web/Views/Shared/_Unauthorized.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>_Unauthorized</title>
</head>
<body>
    <div>
        Доступ запрещен
    </div>
</body>
</html>