eCall.ClientAccount.Web/Models/Complaint/ComplaintAddModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace eCall.ClientAccount.Web.Models.Complaint
{
    public class ComplaintAddModel
    {
        public int ComplaintId { get; set; }
        public int CampaignID { get; set; }
        [Display(Name = "Описание жалобы")]
        public string ComplaintDescription { get; set; }
        [Display(Name = "Кем создано")]
        public string CreatedBy { get; set; }
        [Display(Name = "Когда создано")]
        public DateTime? CreatedOn { get; set; }
        [Display(Name = "Тема жалобы")]
        public string ComplaintTheme { get; set; }
        [Display(Name = "Дата и время поступления жалобы")]
        public DateTime? ComplaintDateTime { get; set; }
        [Display(Name = "Номер телефона клиента")]
        public string PhoneCustomer { get; set; }
        [Display(Name = "Тип абонента")]
        public string TypeCustomer { get; set; }
        [Display(Name = "Коментарии по жалобе")]
        public string ComplaintComment { get; set; }
        [Display(Name = "Информация по жалобе")]
        public string ComplaintInformation { get; set; }
    }
}

eCall.ClientAccount.Web/Models/Complaint/ComplaintDetailsModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace eCall.ClientAccount.Web.Models.Complaint
{
    public class ComplaintDetailsModel
    {
        public int ComplaintId { get; set; }
        public int CampaignID { get; set; }



        [Display(Name = "Описание жалобы")]
        public string ComplaintDescription { get; set; }
        [Display(Name = "Кем создано")]
        public string CreatedBy { get; set; }
        [Display(Name = "Когда создано")]
        public DateTime? CreatedOn { get; set; }
        [Display(Name = "Тема жалобы")]
        public string ComplaintTheme { get; set; }
        [Display(Name = "Дата и время поступления жалобы")]
        public DateTime? ComplaintDateTime { get; set; }
        [Display(Name = "Номер телефона клиента")]
        public string PhoneCustomer { get; set; }
        [Display(Name = "Коментарии по жалобе")]
        public string ComplaintComment { get; set; }
        [Display(Name = "Информация по жалобе")]
        public string ComplaintInformation { get; set; }



        [Display(Name = "Дата и время обработки жалобы")]
        public DateTime UpdatedOn { get; set; }
        [Display(Name = "Кто обрабатывал запись")]
        public string UpdatedBy { get; set; }
        [Display(Name = "ID записи разговора")]
        public string RecordCallId { get; set; }
        [Display(Name = "Оператор")]
        public string Operator { get; set; }
        [Display(Name = "Результат обработки жалобы")]
        public string ComplaintResult { get; set; }
        [Display(Name = "Ответственный")]
        public string Responsible { get; set; }
        [Display(Name = "Коментарий жалобы")]
        public string Comment { get; set; }
    }
}

eCall.ClientAccount.Web/Models/Complaint/ComplaintEditModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace eCall.ClientAccount.Web.Models.Complaint
{
    public class ComplaintEditModel
    {
        public int ComplaintId { get; set; }
        public int CampaignID { get; set; }



        [Display(Name = "Описание жалобы")]
        public string ComplaintDescription { get; set; }
        [Display(Name = "Кем создано")]
        public string CreatedBy { get; set; }
        [Display(Name = "Когда создано")]
        public DateTime? CreatedOn { get; set; }
        [Display(Name = "Тема жалобы")]
        public string ComplaintTheme { get; set; }
        [Display(Name = "Дата и время поступления жалобы")]
        public DateTime? ComplaintDateTime { get; set; }
        [Display(Name = "Номер телефона клиента")]
        public string PhoneCustomer { get; set; }
        [Display(Name = "Коментарии по жалобе")]
        public string ComplaintComment { get; set; }
        [Display(Name = "Информация по жалобе")]
        public string ComplaintInformation { get; set; }



        [Display(Name = "Дата и время обработки жалобы")]
        public DateTime UpdatedOn { get; set; }
        [Display(Name = "Кто обрабатывал запись")]
        public string UpdatedBy { get; set; }
        [Display(Name = "ID записи разговора")]
        public string RecordCallId { get; set; }
        [Display(Name = "Оператор")]
        public string Operator { get; set; }
        [Display(Name = "Результат обработки жалобы")]
        public string ComplaintResult { get; set; }
        [Display(Name = "Ответственный")]
        public string Responsible { get; set; }
        [Display(Name = "Коментарий жалобы")]
        public string Comment { get; set; }        
    }
}

eCall.ClientAccount.Web/Models/Reports/FindReportModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eCall.ClientAccount.Web.Models.Reports
{
    public class FindReportModel
    {
        public int ReportId { get; set; }
        public string Period { get; set; }        
        public int? SkillGroupId { get; set; }
        public IList<SelectListItem> AvailableSkillGroup { get; set; }
        public FindReportModel()
        {
            AvailableSkillGroup = new List<SelectListItem>();
        }
    }
}

eCall.ClientAccount.Web/Controllers/CallRecordController.cs
using eCall.ClientAccount.Services.Services.IPCC;
using eCall.ClientAccount.Services.Services.Security;
using eCall.ClientAccount.Services.Services.TrueRS;
using eCall.ClientAccount.Web.Filter;
using eCall.ClientAccount.Web.Mapper;
using eCall.ClientAccount.Web.Models.CallRecords;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eCall.ClientAccount.Web.Controllers
{
    [ClientAuthorize(Roles = "CAManager, CAUser, CAAdmin")]
    public class CallRecordController : Controller
    {
        #region Fields

        private readonly IWebUserSession _webUserSession;
        private readonly ISkillGroupRecordService _skillGroupRecordService;
        private readonly IAgentRecordService _agentRecordService;
        private readonly IVoiceRecordService _voiceRecordService;
        private readonly IAccessService _accessService;

        #endregion

        #region Constructor

        public CallRecordController(
            IWebUserSession webUserSession,
            ISkillGroupRecordService sgserv,
            IAgentRecordService agentserv,
            IVoiceRecordService vrserv,
            IAccessService accessserv)
        {
            _webUserSession = webUserSession;
            _skillGroupRecordService = sgserv;
            _agentRecordService = agentserv;
            _voiceRecordService = vrserv;
            _accessService = accessserv;
        }

        #endregion

        #region Methods

        public ActionResult RecordIn()
        {
            if(_accessService.AccessCategory(_webUserSession.Id, HttpContext.Request.RawUrl))
            {
                return RedirectToAction("Forbidden", "Error");
            }

            var model = new FindRecordModel
            {
                AvailableSkillGroup = GetAvailableSkillGroup(_webUserSession.Id, "Inbound"),
                AvailableAgent = GetAvailableAgent(_webUserSession.Id, "Inbound")
            };
            return View("RecordIn", model);
        }

        public ActionResult RecordOut()
        {
            if (_accessService.AccessCategory(_webUserSession.Id, HttpContext.Request.RawUrl))
            {
                return RedirectToAction("Forbidden", "Error");
            }

            var model = new FindRecordModel
            {
                AvailableSkillGroup = GetAvailableSkillGroup(_webUserSession.Id, "Outbound"),
                AvailableAgent = GetAvailableAgent(_webUserSession.Id, "Outbound")
            };
            return View("RecordOut", model);
        }

        [HttpPost]
        public ActionResult RecordOutSearch(FindRecordModel findrecord)
        {
            var voiceDto = _voiceRecordService.GetRecordByCustomer(Convert.ToDateTime(findrecord.StartDate), Convert.ToDateTime(findrecord.EndDate), findrecord.SkillGroupId.ToString(), findrecord.Phone, findrecord.AgentId.ToString(), findrecord.Top, _webUserSession.Id, "Outbound", findrecord.MinDuration, findrecord.MaxDuration);
            var model = voiceDto.Select(x => x.ToModel()).ToList();

            return PartialView("RecordOutSearch", model);
        }

        [HttpPost]
        public ActionResult RecordInSearch(FindRecordModel findrecord)
        {
            var dateFrom = Convert.ToDateTime(findrecord.StartDate);
            var dateTo = Convert.ToDateTime(findrecord.EndDate); //.AddDays(1).AddMilliseconds(-1);
            var voiceDto = _voiceRecordService.GetRecordByCustomer(dateFrom, dateTo, findrecord.SkillGroupId.ToString(), findrecord.Phone, findrecord.AgentId.ToString(), findrecord.Top, _webUserSession.Id, "Inbound", findrecord.MinDuration, findrecord.MaxDuration);
            var model = voiceDto.Select(x => x.ToModel()).ToList();
            if (findrecord.EndCall != "All")
            {
                model = model.Where(x => x.EndCall == findrecord.EndCall).ToList();
            }
            //else
            //{
            //    var model = voiceDto.Select(x => x.ToModel()).Where(x => x.EndCall == findrecord.EndCall).ToList();
            //}            

            return PartialView("RecordInSearch", model);
        }

        public ActionResult Details(int id)
        {
            //var recordDto = _voiceRecordService.GetRecordById(id, Server.MapPath("~/Media"), Request.Browser.Browser);
            //var model = recordDto.Select(x => x.ToModel()).ToList();

            var recordDto = _voiceRecordService.GetMP3RecordById(id, Server.MapPath("~/Media"), Request.Browser.Browser);
            
            var model = recordDto.ToModel();
            return PartialView(model);
        }

        //public PartialViewResult RepairIn(string id)
        //{
        //    //string ID = GetSTID(id);
        //    if (id != null && id != "")
        //    {
        //        //SQL.Update(" update vrVoiceRecords set stID=" + ID + " where vrID=" + id);
        //        //SQL.Update(" update vrVoiceRecords set stID=" + ID + " where vrParentID=" + id);
        //    }
        //    return PartialView("Details", new { id });
        //}

        #endregion

        #region Util

        private IList<SelectListItem> GetAvailableSkillGroup(int userId, string type)
        {
            var SkillGroup = new List<SelectListItem>();
            var sg = (_skillGroupRecordService.GetSGRecordForCustomer(userId, type))
                .Select(d => new SelectListItem { Text = d.EnterpriseName, Value = d.SkillsetID.ToString() })
                .ToList();
            if (sg.Count == 0)
                SkillGroup.Add(new SelectListItem { Text = "Нет доступных SkillGroup", Value = "", Selected = true });
            else
            {
                SkillGroup.Add(new SelectListItem { Text = "Все SkillGroup", Value = "-1", Selected = true });
                SkillGroup.AddRange(sg);
            }                
            return SkillGroup;
        }

        private IList<SelectListItem> GetAvailableAgent(int userId, string type)
        {
            var Agent = new List<SelectListItem>();

            var agent = (_agentRecordService.GetAgentBySG(userId, type))
                .Select(d => new SelectListItem { Text = d.EnterpriseName, Value = d.SkillTargetID.ToString() })
                .ToList();
            if (agent.Count == 0)
                Agent.Add(new SelectListItem { Text = "Нет доступных операторов", Value = "", Selected = true });
            else
            {
                Agent.Add(new SelectListItem { Text = "Все операторы", Value = "-1", Selected = true });
                Agent.AddRange(agent);
            }
                
            return Agent;
        }

        #endregion        
    }
}

eCall.ClientAccount.Web/Controllers/ReportController.cs
using eCall.ClientAccount.Services.Services.Complaints;
using eCall.ClientAccount.Services.Services.Reports;
using eCall.ClientAccount.Services.Services.Security;
using eCall.ClientAccount.Web.Filter;
using eCall.ClientAccount.Web.Mapper;
using eCall.ClientAccount.Web.Models.Complaint;
using eCall.ClientAccount.Web.Models.Reports;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Xml;
using System.Xml.Serialization;

namespace eCall.ClientAccount.Web.Controllers
{
    [ClientAuthorize(Roles = "CAManager, CAUser, CAAdmin")]
    public class ReportController : Controller
    {
        #region Fields

        private readonly IReportService _reportService;
        private readonly IWebUserSession _webUserSession;
        private readonly IAccessService _accessService;
        private readonly ISkillGroupReportService _skillGroupReportService;
        private readonly IComplaintService _complaintService;

        #endregion

        #region Constructor

        public ReportController(
            IReportService repserv,
            IWebUserSession webUserSession,
            IAccessService accessserv,
            ISkillGroupReportService sgserv,
            IComplaintService complaintserv)
        {
            _reportService = repserv;
            _webUserSession = webUserSession;
            _accessService = accessserv;
            _skillGroupReportService = sgserv;
            _complaintService = complaintserv;
        }

        #endregion

        #region Methods

        public ActionResult Index(int reportId)
        {
            if (_accessService.AccessReport(_webUserSession.Id, reportId))
            {
                return RedirectToAction("Forbidden", "Error");
            }

            var model = new FindReportModel
            {
                ReportId = reportId,
                AvailableSkillGroup = GetAvailableSkillGroup(_webUserSession.Id)
            };

            return View(model);
        }

        // GET: ReportDisplay
        public JsonResult ReportDisplay(int? reportId, string skillgroupid, string StartDate, string EndDate)
        {
            if (reportId == null)
                return Json("", JsonRequestBehavior.AllowGet);

            var jsondata = new List<Dictionary<string, object>>();

            jsondata = _reportService.ExecuteReport((int)reportId, skillgroupid, StartDate, EndDate, _webUserSession.Id);
            
            var jsonResult = Json(jsondata, JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        public ActionResult Complaint()
        {
            //var complaintDto = _complaintService.GetAllComplaint(_webUserSession.Id);
            //var model = complaintDto.Select(x => x.ToModel()).ToList();

            return View(/*model*/);
        }

        public ActionResult ComplaintSearch(string sd, string ed, string phone, string rescomplaint)
        {
            var complaintDto = _complaintService.GetAllComplaint(_webUserSession.Id, sd, ed, phone, rescomplaint);
            var model = complaintDto.Select(x => x.ToModel()).ToList();

            return PartialView(model);
        }

        [HttpGet]
        public ActionResult DetailsComplaint(int Id)
        {
            var complaintDto = _complaintService.GetComplaintById(Id, _webUserSession.Id);
            var model = complaintDto.ToModel();

            return View(model);
        }

        [HttpGet]
        public ActionResult AddComplaint()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddComplaint(ComplaintAddModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var complaintDto = model.ToEntityAdd();
            _complaintService.CreateComplaint(complaintDto, _webUserSession.Id);
            
            return RedirectToAction("Complaint"); 
        }

        [ClientAuthorize(Roles = "CAManager")]
        [HttpGet]
        public ActionResult EditComplaint(int Id)
        {
            var complaintDto = _complaintService.GetComplaintById(Id, _webUserSession.Id);
            var model = complaintDto.ToModel();

            return View(model);
        }

        [ClientAuthorize(Roles = "CAManager")]
        [HttpPost]
        public ActionResult EditComplaint(ComplaintModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var complaintDto = model.ToEntity();
            _complaintService.UpdateComplaint(complaintDto, _webUserSession.Id);

            return RedirectToAction("Complaint"); 
        }

        
        #endregion

        #region Util

        private IList<SelectListItem> GetAvailableSkillGroup(int userId)
        {
            var SkillGroup = new List<SelectListItem>();
            var sg = (_skillGroupReportService.GetSGRecordForCustomer(userId))
                .Select(d => new SelectListItem { Text = d.EnterpriseName, Value = d.SkillTargetID.ToString() })
                .ToList();
            if (sg.Count == 0)
                SkillGroup.Add(new SelectListItem { Text = "Нет доступных SkillGroup", Value = "", Selected = true });
            else
            {
                SkillGroup.Add(new SelectListItem { Text = "Все SkillGroup", Value = "-1", Selected = true });
                SkillGroup.AddRange(sg);
            }
            return SkillGroup;
        }
        

        #endregion
    }
}

eCall.ClientAccount.Web/Views/Report/ComplaintSearch.cshtml
@model IEnumerable<eCall.ClientAccount.Web.Models.Complaint.ComplaintModel>


@*@section PageLevelPluginsStyles{
    @Styles.Render("~/Content/global/plugins/datatables/datatables.min.css")
    @Styles.Render("~/Content/daterangepicker.css")
}*@

@*<div class="row">
    <div class="col-md-12">
        <div class="portlet box red">
            <div class="portlet-title">
                <div class="caption font-dark">
                    <i class="fa fa-bars font-dark"></i>
                    <span class="caption-subject bold uppercase">Список жалоб</span>
                </div>

                @if (Request.IsAuthenticated && User.IsInRole("CAUser"))
    {
                <div class="actions">
                    <div class="form-actions no-color">
                        <a id="sample_editable_1_new" href="@Url.Action("AddComplaint")" class="btn sbold green">Создать <i class="fa fa-plus"></i></a>
                    </div>
                </div>
}
            </div>
            <div class="portlet-body" id="portlet-body">
                <table class="table table-striped table-bordered table-hover" id="sample_3">
                    <thead>
                        <tr align="center" valign="center">
                            <th>
                                Действия
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ComplaintId)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ComplaintDateTime)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.PhoneCustomer)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.TypeCustomer)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.RecordCallId)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.CreatedOn)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ComplaintResult)
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td class="btn-group btn-group-solid" style="display:flex;white-space:nowrap" align="center">
                                    @if (Request.IsAuthenticated && User.IsInRole("CAManager"))
                                    {
                                        <a class="btn btn-icon-only yellow-saffron popovers" style="margin-right:0" data-container="body" data-trigger="hover" data-content="Изменить" data-placement="bottom" href="@Url.Action("EditComplaint", "Report", new { id = item.ComplaintId })">
                                            <i class="fa fa-pencil"></i>
                                        </a>
                                    }
                                    <a class="btn btn-icon-only blue popovers" style="margin-right:0" data-container="body" data-trigger="hover" data-content="Детали" data-placement="bottom" href="@Url.Action("DetailsComplaint", "Report", new { id = item.ComplaintId })">
                                        <i class="fa fa-info"></i>
                                    </a>
                                </td>
                                <td>@Html.DisplayFor(modelItem => item.ComplaintId)</td>
                                <td>@Html.DisplayFor(modelItem => item.ComplaintDateTime)</td>
                                <td>@Html.DisplayFor(modelItem => item.PhoneCustomer)</td>
                                <td>@Html.DisplayFor(modelItem => item.TypeCustomer)</td>
                                <td>
                                    @if (item.RecordCallId != null)
                                    {
                                        <a class="compItem" style="margin-right:0" data-container="body" data-trigger="hover" data-content="Играть" data-placement="bottom" href="@Url.Action("Details", "CallRecord", new { id = item.RecordCallId })">
                                            @item.RecordCallId.ToString()
                                        </a>
                                    }
                                </td>
                                <td>@Html.DisplayFor(modelItem => item.CreatedOn)</td>
                                <td>@Html.DisplayFor(modelItem => item.ComplaintResult)</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>*@

<div class="row">
    <div class="col-md-12">
        <!-- BEGIN EXAMPLE TABLE PORTLET-->
        <div class="portlet box red">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-globe"></i>Список жалоб
                </div>
                <div class="tools"> </div>
            </div>
            <div class="portlet-body">
                @if (Request.IsAuthenticated && User.IsInRole("CAUser"))
    {
            <div class="actions">
                <div class="form-actions no-color">
                    <a id="sample_editable_1_new" href="@Url.Action("AddComplaint")" class="btn btn-success sbold ">Создать <i class="fa fa-plus"></i></a>
                </div>
            </div>
            <br />
}

                <table class="table table-striped table-bordered table-hover" id="sample_2">
                    <thead>
                        <tr>
                            <th> Действия </th>
                            <th> @Html.DisplayNameFor(model => model.ComplaintId) </th>
                            <th> @Html.DisplayNameFor(model => model.ComplaintTheme) </th>
                            <th> @Html.DisplayNameFor(model => model.Operator) </th>
                            <th> @Html.DisplayNameFor(model => model.ComplaintDateTime) </th>
                            <th> @Html.DisplayNameFor(model => model.PhoneCustomer) </th>
                            <th> @Html.DisplayNameFor(model => model.TypeCustomer) </th>
                            <th> @Html.DisplayNameFor(model => model.RecordCallId) </th>
                            <th> @Html.DisplayNameFor(model => model.CreatedOn) </th>
                            <th> @Html.DisplayNameFor(model => model.ComplaintResult) </th>
                            <th> @Html.DisplayNameFor(model => model.UpdatedOn) </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        { 
                        <tr>
                            <td>
                                @if (Request.IsAuthenticated && User.IsInRole("CAManager"))
        {
                        <a class="btn btn-icon-only yellow-saffron popovers" style="margin-right:0" data-container="body" data-trigger="hover" data-content="Изменить" data-placement="bottom" href="@Url.Action("EditComplaint", "Report", new { id = item.ComplaintId })">
                            <i class="fa fa-pencil"></i>
                        </a>
}
                                <a class="btn btn-icon-only blue popovers" style="margin-right:0" data-container="body" data-trigger="hover" data-content="Детали" data-placement="bottom" href="@Url.Action("DetailsComplaint", "Report", new { id = item.ComplaintId })">
                                    <i class="fa fa-info"></i>
                                </a>
                            </td>
                            <td> @Html.DisplayFor(modelItem => item.ComplaintId) </td>
                            <td> @Html.DisplayFor(modelItem => item.ComplaintTheme) </td>
                            <td> @Html.DisplayFor(modelItem => item.Operator) </td>
                            <td> @Html.DisplayFor(modelItem => item.ComplaintDateTime) </td>
                            <td> @Html.DisplayFor(modelItem => item.PhoneCustomer) </td>
                            <td> @Html.DisplayFor(modelItem => item.TypeCustomer) </td>
                            <td>
                                @if (item.RecordCallId != null)
        {
                        <a class="compItem" style="margin-right:0" data-container="body" data-trigger="hover" data-content="Играть" data-placement="bottom" href="@Url.Action("Details", "CallRecord", new { id = item.RecordCallId })">
                            @item.RecordCallId.ToString()
                        </a>
                        @*@Url.Action("Details", "CallRecord", new { id = item.RecordCallId })*@
                        @*@Html.ActionLink(item.RecordCallId.ToString(), "Details", "CallRecord", new { id = item.RecordCallId }, null)*@
}
                            </td>
                            <td> @Html.DisplayFor(modelItem => item.CreatedOn) </td>
                            <td> @Html.DisplayFor(modelItem => item.ComplaintResult) </td>
                            <td> @Html.DisplayFor(modelItem => item.UpdatedOn)</td>
                        </tr>
}                        
                    </tbody>
                </table>
            </div>
        </div>
        <!-- END EXAMPLE TABLE PORTLET-->
    </div>
</div>

<div id="modDialog" class="modal fade" tabindex="-1" aria-hidden="true">
    <div id="dialogContent" class="modal-dialog modal-lg"></div>
</div>

<script src="~/Scripts/Pages/table-datatables-buttons.min.js"></script>
    @*<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    @Scripts.Render("~/Content/global/scripts/datatable.js")
    @Scripts.Render("~/Content/global/plugins/datatables/datatables.min.js")
    @Scripts.Render("~/Content/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js")
    @Scripts.Render("~/Scripts/moment.min.js")
    @Scripts.Render("~/Scripts/moment-with-locales.min.js")
    <script src="~/Scripts/daterangepicker.js"></script>
    <script src="~/Content/global/plugins/morris/morris.min.js" type="text/javascript"></script>
    <script src="~/Content/global/plugins/morris/raphael-min.js" type="text/javascript"></script>*@




    @*@Scripts.Render("~/Scripts/Pages/table-datatables-managed.js")*@
    @*<script src="~/Scripts/Pages/table-datatables-buttons.min.js"></script>*@
    @*@Scripts.Render("~/Scripts/Pages/date-time-pickers.js")
    @Scripts.Render("~/Scripts/Pages/ui-blockui.js")*@

    <script type="text/javascript">

        $(function () {
            $.ajaxSetup({ cache: false });
            $(".compItem").click(function (e) {

                e.preventDefault();
                $.get(this.href, function (data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
            
        })
    </script>

    @*<script type="text/javascript">
        $(document).ready(function () {
            $("#btnExport").click(function (e) {
                window.open('data:application/vnd.ms-excel,' + encodeURIComponent($('table[id$=sample_3]').html()));
                e.preventDefault();
            });
        });
    </script>*@